-- =============================================================================
-- Migration 001: Portal de Proveedores — tablas, RLS y append-only
-- Ejecutar en el SQL Editor de Supabase (una sola vez, en orden)
--
-- Prefijo `pp_` = Portal Proveedores. NO confundir con el rol `admin_proveedor`
-- que ya existe en la app y pertenece a Trazabilidad Contable.
--
-- Leer junto con docs/ARQUITECTURA.md §4 y §5.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. pp_proveedores — espejo local del maestro de terceros de SIESA
--    Acá viven los campos que SIESA no conoce: el tope y el bloqueo.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pp_proveedores (
  nit             VARCHAR(15)  PRIMARY KEY,
  id_tercero      VARCHAR(15)  NOT NULL,
  razon_social    TEXT,
  porcentaje_max  NUMERIC(5,2),
  bloqueado       BOOLEAN      NOT NULL DEFAULT false,
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT pp_proveedores_pct_valido
    CHECK (porcentaje_max IS NULL OR porcentaje_max >= 0)
);

-- Este comentario no es decorativo: NULL y 0 se confunden solos, y confundirlos
-- congela a todo proveedor que nadie configuró todavía.
COMMENT ON COLUMN pp_proveedores.porcentaje_max IS
  'Tope de subida del COSTO NETO, en puntos porcentuales (5.00 = 5%). '
  'NULL = SIN TOPE. 0 = ninguna subida permitida. No son lo mismo.';

COMMENT ON COLUMN pp_proveedores.id_tercero IS
  'F212_ID_TERCERO de SIESA. Hoy coincide con el NIT, pero son campos distintos '
  'y pueden divergir: este es el que va al conector.';

-- ---------------------------------------------------------------------------
-- 2. pp_cuentas — una fila por sucursal habilitada. Es la unidad de acceso.
--    La identidad en Supabase Auth es un email sintético nit-sucursal@…
--    (ARQUITECTURA §3.2). `correo_notificacion` es el correo REAL y solo
--    sirve para mandarle avisos: nunca es credencial.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pp_cuentas (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nit                  VARCHAR(15)  NOT NULL REFERENCES pp_proveedores(nit) ON DELETE RESTRICT,
  sucursal             VARCHAR(3)   NOT NULL,
  nombre_sucursal      TEXT,
  correo_notificacion  TEXT,
  user_id              UUID         UNIQUE REFERENCES auth.users(id) ON DELETE SET NULL,
  estado               VARCHAR(20)  NOT NULL DEFAULT 'sin_invitar',
  created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT pp_cuentas_nit_sucursal UNIQUE (nit, sucursal),
  CONSTRAINT pp_cuentas_estado_valido
    CHECK (estado IN ('sin_invitar','invitado','activo','suspendido'))
);

CREATE INDEX IF NOT EXISTS idx_pp_cuentas_nit     ON pp_cuentas(nit);
CREATE INDEX IF NOT EXISTS idx_pp_cuentas_user    ON pp_cuentas(user_id);
CREATE INDEX IF NOT EXISTS idx_pp_cuentas_estado  ON pp_cuentas(estado);

-- ---------------------------------------------------------------------------
-- 3. pp_invitaciones — enlace de un solo uso para que el proveedor fije su clave
--    NUNCA se manda una contraseña por correo (ARQUITECTURA §3.4).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pp_invitaciones (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cuenta_id   BIGINT       NOT NULL REFERENCES pp_cuentas(id) ON DELETE CASCADE,
  token_hash  TEXT         NOT NULL UNIQUE,
  expira_at   TIMESTAMPTZ  NOT NULL,
  usado_at    TIMESTAMPTZ,
  creado_por  TEXT,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Se guarda el HASH, jamás el token. Una tabla con tokens en claro es una tabla
-- desde la que cualquiera con acceso de lectura se hace pasar por un proveedor.
COMMENT ON COLUMN pp_invitaciones.token_hash IS
  'SHA-256 del token. El token en claro existe UNA vez, en el correo. Si se '
  'pierde, se emite otro: no se puede recuperar de acá, y así debe ser.';

CREATE INDEX IF NOT EXISTS idx_pp_invitaciones_cuenta ON pp_invitaciones(cuenta_id);

-- ---------------------------------------------------------------------------
-- 4. pp_cotizaciones — snapshot de la consulta de SIESA
--    La consulta NO acepta paginación y trae TODOS los proveedores de una, así
--    que no se puede llamar en un request de usuario (CONTRATO-SIESA §1bis.e).
--    Un cron la vuelca acá y el portal lee de esta tabla.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pp_cotizaciones (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clave             TEXT         NOT NULL UNIQUE,
  clave_item        TEXT         NOT NULL,
  id_tercero        VARCHAR(15)  NOT NULL,
  nit               VARCHAR(15)  NOT NULL,
  sucursal          VARCHAR(3)   NOT NULL,
  item              INTEGER      NOT NULL,
  descripcion_item  TEXT,
  unidad_medida     VARCHAR(4)   NOT NULL,
  fecha_activacion  DATE         NOT NULL,
  precio            NUMERIC(19,4),
  impuestos         JSONB        NOT NULL DEFAULT '[]'::jsonb,
  descuentos        JSONB        NOT NULL DEFAULT '[]'::jsonb,
  sincronizado_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- `clave` es la llave natural de SIESA con la fecha adentro; `clave_item` es el
-- renglón editable del portal, SIN fecha. Un ítem+U.M. puede tener varias filas
-- —el precio vigente y los futuros—, y la vigente es la de mayor fecha no futura
-- (CONTRATO-SIESA §2.3).
COMMENT ON COLUMN pp_cotizaciones.clave_item IS
  'COP|id_tercero|sucursal|item|unidad_medida — el renglón que ve el proveedor. '
  'La U.M. es parte de la llave: un ítem NO tiene un precio, tiene uno por unidad.';

CREATE INDEX IF NOT EXISTS idx_pp_cotizaciones_item     ON pp_cotizaciones(clave_item);
CREATE INDEX IF NOT EXISTS idx_pp_cotizaciones_cuenta   ON pp_cotizaciones(id_tercero, sucursal);
CREATE INDEX IF NOT EXISTS idx_pp_cotizaciones_fecha    ON pp_cotizaciones(fecha_activacion DESC);

-- ---------------------------------------------------------------------------
-- 5. pp_firmas — APPEND-ONLY. Ver el bloque de triggers al final.
--    El trazo es la parte visible; lo que hace válida la firma es el hash del
--    contenido firmado (ARQUITECTURA §8).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pp_firmas (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cuenta_id     BIGINT       NOT NULL REFERENCES pp_cuentas(id) ON DELETE RESTRICT,
  user_id       UUID,
  payload_hash  TEXT         NOT NULL,
  trazo         TEXT,
  ip            INET,
  user_agent    TEXT,
  firmado_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON COLUMN pp_firmas.payload_hash IS
  'SHA-256 de item+unidad+precio_actual+precio_propuesto+descuentos+fecha_activacion+cuenta_id. '
  'Si después cambia cualquiera de esos campos, el hash deja de coincidir y la '
  'firma queda inválida. Una firma que no se rompe al cambiar lo firmado no prueba nada.';

COMMENT ON COLUMN pp_firmas.firmado_at IS
  'Hora del SERVIDOR. Nunca la que manda el cliente: el reloj del firmante no es prueba.';

CREATE INDEX IF NOT EXISTS idx_pp_firmas_cuenta ON pp_firmas(cuenta_id);

-- ---------------------------------------------------------------------------
-- 6. pp_solicitudes_precio — el corazón del sistema
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pp_solicitudes_precio (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cuenta_id               BIGINT       NOT NULL REFERENCES pp_cuentas(id) ON DELETE RESTRICT,

  -- Identidad del renglón, tal como se le manda al conector.
  clave_item              TEXT         NOT NULL,
  item                    INTEGER      NOT NULL,
  descripcion_item        TEXT,
  unidad_medida           VARCHAR(4)   NOT NULL,

  -- Lo que regía cuando se propuso. Congelado: es la base del cálculo y de la firma.
  precio_actual           NUMERIC(19,4) NOT NULL,
  descuentos_actuales     JSONB        NOT NULL DEFAULT '[]'::jsonb,
  impuestos_vigentes      JSONB        NOT NULL DEFAULT '[]'::jsonb,
  costo_neto_actual       NUMERIC(19,4) NOT NULL,

  -- Lo propuesto.
  precio_propuesto        NUMERIC(19,4) NOT NULL,
  descuentos_propuestos   JSONB        NOT NULL DEFAULT '[]'::jsonb,
  costo_neto_propuesto    NUMERIC(19,4) NOT NULL,
  variacion_pct           NUMERIC(9,4)  NOT NULL,
  porcentaje_max_vigente  NUMERIC(5,2),

  fecha_activacion        DATE         NOT NULL,
  notas                   VARCHAR(255),

  estado                  VARCHAR(20)  NOT NULL DEFAULT 'pendiente',
  motivo_rechazo          TEXT,
  firma_id                BIGINT       NOT NULL REFERENCES pp_firmas(id) ON DELETE RESTRICT,

  siesa_aplicado_at       TIMESTAMPTZ,
  siesa_payload           JSONB,
  siesa_respuesta         JSONB,

  creado_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
  resuelto_at             TIMESTAMPTZ,
  resuelto_por            TEXT,
  updated_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT pp_solicitudes_estado_valido
    CHECK (estado IN ('pendiente','aprobada','rechazada','aplicada','fallida')),

  -- Un rechazo sin motivo es un rechazo que el proveedor no puede accionar:
  -- vuelve a proponer lo mismo y vuelve a chocar. La base lo exige.
  CONSTRAINT pp_solicitudes_rechazo_con_motivo
    CHECK (estado <> 'rechazada' OR (motivo_rechazo IS NOT NULL AND btrim(motivo_rechazo) <> '')),

  -- Aplicada sin marca de empuje sería una solicitud que dice estar en el ERP sin
  -- que nadie sepa cuándo entró — justo el agujero por donde se cuelan los duplicados.
  CONSTRAINT pp_solicitudes_aplicada_con_marca
    CHECK (estado <> 'aplicada' OR siesa_aplicado_at IS NOT NULL)
);

-- El candado que impide dos propuestas vivas sobre el mismo renglón.
-- Parcial a propósito: el histórico puede tener todas las resueltas que quiera.
CREATE UNIQUE INDEX IF NOT EXISTS idx_pp_solicitudes_pendiente_unica
  ON pp_solicitudes_precio (cuenta_id, clave_item)
  WHERE estado = 'pendiente';

CREATE INDEX IF NOT EXISTS idx_pp_solicitudes_cuenta  ON pp_solicitudes_precio(cuenta_id);
CREATE INDEX IF NOT EXISTS idx_pp_solicitudes_estado  ON pp_solicitudes_precio(estado);
CREATE INDEX IF NOT EXISTS idx_pp_solicitudes_creado  ON pp_solicitudes_precio(creado_at DESC);

-- Cola del empuje a SIESA: aprobadas que todavía no se marcaron. Es la consulta
-- del reintento, y es la que tiene que ser rápida y exacta.
CREATE INDEX IF NOT EXISTS idx_pp_solicitudes_por_aplicar
  ON pp_solicitudes_precio (id)
  WHERE estado = 'aprobada' AND siesa_aplicado_at IS NULL;

COMMENT ON COLUMN pp_solicitudes_precio.siesa_aplicado_at IS
  'Ancla de idempotencia. Se marca ANTES de dar por cerrada la operación. En '
  'Traslados, sin un ancla así, el mismo documento se mandó a SIESA tres veces.';

COMMENT ON COLUMN pp_solicitudes_precio.porcentaje_max_vigente IS
  'Snapshot del tope que regía al proponer. Si el admin lo cambia después, el '
  'histórico sigue diciendo cuál se aplicó ese día.';

-- ---------------------------------------------------------------------------
-- 7. pp_auditoria — APPEND-ONLY. Toda transición de estado deja rastro.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pp_auditoria (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entidad          VARCHAR(40)  NOT NULL,
  entidad_id       TEXT,
  accion           VARCHAR(60)  NOT NULL,
  estado_anterior  VARCHAR(20),
  estado_nuevo     VARCHAR(20),
  actor_user_id    UUID,
  actor_rol        VARCHAR(30),
  detalle          JSONB,
  ip               INET,
  creado_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pp_auditoria_entidad ON pp_auditoria(entidad, entidad_id);
CREATE INDEX IF NOT EXISTS idx_pp_auditoria_creado  ON pp_auditoria(creado_at DESC);

-- =============================================================================
-- APPEND-ONLY de verdad
--
-- Quitar la política de UPDATE en RLS no alcanza: el backend se conecta con la
-- SERVICE KEY, que pasa por encima de RLS. O sea que un bug nuestro podría editar
-- una firma sin que nada lo frene.
--
-- Un trigger sí ata a todos, service key incluida. Una firma que se puede editar
-- no es una firma, y una auditoría que se puede reescribir no es una auditoría.
-- =============================================================================

CREATE OR REPLACE FUNCTION pp_solo_insertar() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'La tabla % es append-only: no admite % (intento sobre id=%)',
    TG_TABLE_NAME, TG_OP, COALESCE(OLD.id::text, '?');
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_pp_firmas_append_only ON pp_firmas;
CREATE TRIGGER trg_pp_firmas_append_only
  BEFORE UPDATE OR DELETE ON pp_firmas
  FOR EACH ROW EXECUTE FUNCTION pp_solo_insertar();

DROP TRIGGER IF EXISTS trg_pp_auditoria_append_only ON pp_auditoria;
CREATE TRIGGER trg_pp_auditoria_append_only
  BEFORE UPDATE OR DELETE ON pp_auditoria
  FOR EACH ROW EXECUTE FUNCTION pp_solo_insertar();

-- ---------------------------------------------------------------------------
-- updated_at automático
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION pp_touch_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_pp_proveedores_touch ON pp_proveedores;
CREATE TRIGGER trg_pp_proveedores_touch BEFORE UPDATE ON pp_proveedores
  FOR EACH ROW EXECUTE FUNCTION pp_touch_updated_at();

DROP TRIGGER IF EXISTS trg_pp_cuentas_touch ON pp_cuentas;
CREATE TRIGGER trg_pp_cuentas_touch BEFORE UPDATE ON pp_cuentas
  FOR EACH ROW EXECUTE FUNCTION pp_touch_updated_at();

DROP TRIGGER IF EXISTS trg_pp_solicitudes_touch ON pp_solicitudes_precio;
CREATE TRIGGER trg_pp_solicitudes_touch BEFORE UPDATE ON pp_solicitudes_precio
  FOR EACH ROW EXECUTE FUNCTION pp_touch_updated_at();

-- =============================================================================
-- RLS — la red debajo del trapecio
--
-- El aislamiento REAL lo hace el middleware del backend, que deriva el cuenta_id
-- del JWT (ARQUITECTURA §5). Esto es la segunda capa: el frontend tiene sesión
-- de Supabase con la anon key, así que si alguien consulta las tablas
-- directamente —o si mañana un endpoint se escribe sin filtro— la base corta.
--
-- Un proveedor viendo los precios de otro no es un bug menor: es un problema
-- legal. Por eso van dos capas y no una.
-- =============================================================================

ALTER TABLE pp_proveedores        ENABLE ROW LEVEL SECURITY;
ALTER TABLE pp_cuentas            ENABLE ROW LEVEL SECURITY;
ALTER TABLE pp_invitaciones       ENABLE ROW LEVEL SECURITY;
ALTER TABLE pp_cotizaciones       ENABLE ROW LEVEL SECURITY;
ALTER TABLE pp_firmas             ENABLE ROW LEVEL SECURITY;
ALTER TABLE pp_solicitudes_precio ENABLE ROW LEVEL SECURITY;
ALTER TABLE pp_auditoria          ENABLE ROW LEVEL SECURITY;

-- Sin políticas, RLS niega TODO. Cada permiso de abajo es explícito y mínimo.

/**
 * La cuenta del usuario que está consultando.
 *
 * SECURITY DEFINER para poder leer pp_cuentas sin caer en la recursión de
 * evaluar la política de pp_cuentas dentro de la política de pp_cuentas.
 * STABLE para que Postgres la evalúe una vez por consulta y no por fila.
 */
CREATE OR REPLACE FUNCTION pp_cuenta_actual() RETURNS BIGINT AS $$
  SELECT id FROM pp_cuentas
   WHERE user_id = auth.uid()
     AND estado = 'activo'
   LIMIT 1;
$$ LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public;

-- --- pp_cuentas: el proveedor ve SU cuenta y nada más -----------------------
DROP POLICY IF EXISTS pp_cuentas_propia ON pp_cuentas;
CREATE POLICY pp_cuentas_propia ON pp_cuentas
  FOR SELECT TO authenticated
  USING (user_id = auth.uid());

-- --- pp_cotizaciones: solo las de su NIT+sucursal ---------------------------
DROP POLICY IF EXISTS pp_cotizaciones_propias ON pp_cotizaciones;
CREATE POLICY pp_cotizaciones_propias ON pp_cotizaciones
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM pp_cuentas c
       WHERE c.id = pp_cuenta_actual()
         AND c.nit = pp_cotizaciones.nit
         AND c.sucursal = pp_cotizaciones.sucursal
    )
  );

-- --- pp_solicitudes_precio: solo las propias, y solo lectura ----------------
-- La escritura pasa SIEMPRE por el backend: es el único lugar donde se valida el
-- tope contra el precio que el servidor leyó de SIESA. Un INSERT directo desde el
-- navegador se saltearía esa validación entera.
DROP POLICY IF EXISTS pp_solicitudes_propias ON pp_solicitudes_precio;
CREATE POLICY pp_solicitudes_propias ON pp_solicitudes_precio
  FOR SELECT TO authenticated
  USING (cuenta_id = pp_cuenta_actual());

-- --- pp_firmas: el proveedor ve las suyas, no las escribe desde el cliente --
DROP POLICY IF EXISTS pp_firmas_propias ON pp_firmas;
CREATE POLICY pp_firmas_propias ON pp_firmas
  FOR SELECT TO authenticated
  USING (cuenta_id = pp_cuenta_actual());

-- --- pp_proveedores, pp_invitaciones, pp_auditoria: SIN política ------------
-- Deliberado. `pp_proveedores` guarda `porcentaje_max`: el tope es información de
-- configuración interna, y el proveedor solo necesita conocerlo en el momento en
-- que lo choca — el 422 se lo dice con el número exacto. `pp_invitaciones` guarda
-- hashes de token. `pp_auditoria` es el registro de todos. Ninguna se expone al
-- cliente: se leen únicamente con la service key, desde el backend.
