-- ---------------------------------------------------------------------------
-- 006 — Una solicitud, muchos productos (y los impuestos editables)
-- ---------------------------------------------------------------------------
--
-- QUÉ RESUELVE
-- `pp_solicitudes_precio` es UNA FILA = UN PRODUCTO. Un proveedor que renegocia
-- cuarenta referencias tiene que firmar cuarenta veces, y compras las revisa de
-- a una sin ver que son la misma negociación. Acá se parte en cabecera + líneas:
--
--     pp_solicitudes        → el paquete. Tiene LA firma. Una solicitud, una firma.
--     pp_solicitud_lineas   → cada producto. Tiene SU estado.
--
-- POR QUÉ LA FIRMA VA EN LA CABECERA Y EL ESTADO EN LA LÍNEA
-- Son dos hechos, de dos personas distintas. La firma es del PROVEEDOR y cubre lo
-- que él propuso: si el admin aprueba tres líneas y rechaza una, lo que el
-- proveedor propuso no cambió, así que la firma sigue siendo válida. El estado es
-- la decisión de MERKAHORRO, y es por producto porque se aprueba por producto.
--
-- Por eso el hash de la firma tiene que cubrir TODAS las líneas: si alguien
-- agrega, saca o edita una, la firma deja de coincidir. Una firma que no se rompe
-- al cambiar lo firmado no prueba nada (ver el comentario de pp_firmas.payload_hash).
--
-- POR QUÉ LA CABECERA NO TIENE `estado`
-- Se deriva de las líneas (vista `pp_solicitudes_resumen`, más abajo). Guardarlo
-- sería una segunda fuente de verdad, y las dos se van a contradecir el día que
-- alguien apruebe una línea sin acordarse de actualizar el padre.
--
-- LO QUE TRAE DE NUEVO: `impuestos_propuestos`
-- Hasta hoy los impuestos (ICO, IBU3) eran de solo lectura y se RE-EMITÍAN tal
-- cual desde la cotización vigente. Ahora el proveedor los puede editar, así que
-- hay que guardar qué propuso, no solamente qué había.
--
-- Un impuesto NO entra en el tope de %. El tope compara costo neto contra costo
-- neto, y meter los impuestos adentro lo AFLOJARÍA: un ítem de $10.000 con ICO
-- $5.000 que sube a $11.000 pasaría de +10 % a +6,67 %. La guarda que hoy funciona
-- quedaría más permisiva justo en los ítems que más plata mueven.
--
-- El control de un impuesto es otro, porque un impuesto no se negocia: lo fija la
-- ley. Cambiarlo dispara aviso al proveedor, correo a compras y bandera en la
-- bandeja. O sea: lo mira una persona, que es lo que corresponde. Un umbral
-- porcentual sobre un hecho legal no significa nada.
--
-- LA RÉPLICA A SUCURSALES HERMANAS (`origen` / `replica_de_id`)
-- Un mismo NIT puede tener la sucursal de Copacabana y la del resto — "COPA ZONA
-- 2 RAMA" y "ZONA 2 RAMA" son el mismo acuerdo partido por zona de entrega. La
-- propuesta se replica a la hermana AUTOMÁTICAMENTE y en SILENCIO: el reparto por
-- sede es interno de Merkahorro, el proveedor no lo maneja ni le sirve.
--
-- Silencio para el PROVEEDOR, no para compras. El admin sí ve la línea replicada,
-- y tiene que verla: medido sobre datos reales el 2026-09-06, de 521 renglones
-- comparados entre hermanas, **16 ya tienen precio distinto hoy** (ZONA 2 NIVEA:
-- $17.260 contra $17.290). Replicar sin que nadie lo vea pisa una diferencia que
-- alguien puso a propósito.
--
-- El silencio lo hace la BASE, no el cuidado de quien escribe la consulta: la
-- política de RLS del punto 5 no le deja ver al proveedor las líneas replicadas.
--
-- QUÉ PASA CON LA TABLA VIEJA
-- Se conserva y se copia. No se borra acá: primero se verifica el backfill contra
-- producción. Ver el punto 7.
-- ---------------------------------------------------------------------------


-- ===========================================================================
-- 1. Cabecera — el paquete que se firma de una sola vez
-- ===========================================================================
CREATE TABLE IF NOT EXISTS pp_solicitudes (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cuenta_id   BIGINT       NOT NULL REFERENCES pp_cuentas(id) ON DELETE RESTRICT,
  firma_id    BIGINT       NOT NULL REFERENCES pp_firmas(id)  ON DELETE RESTRICT,
  creado_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE pp_solicitudes IS
  'El paquete de propuestas que el proveedor firma de una sola vez. El estado NO '
  'vive acá: se deriva de las líneas (vista pp_solicitudes_resumen).';

COMMENT ON COLUMN pp_solicitudes.cuenta_id IS
  'Quién PROPONE y FIRMA. No es necesariamente dónde aterriza cada línea: una '
  'línea replicada a la sucursal hermana lleva su propio cuenta_destino_id.';

COMMENT ON COLUMN pp_solicitudes.firma_id IS
  'UNA firma por solicitud. Su payload_hash cubre TODAS las líneas: agregar, '
  'sacar o editar una tiene que romper la firma.';

CREATE INDEX IF NOT EXISTS idx_pp_solicitudes_cuenta ON pp_solicitudes(cuenta_id);
CREATE INDEX IF NOT EXISTS idx_pp_solicitudes_creado ON pp_solicitudes(creado_at DESC);


-- ===========================================================================
-- 2. Líneas — un producto cada una, con su estado y su propio empuje
-- ===========================================================================
CREATE TABLE IF NOT EXISTS pp_solicitud_lineas (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  solicitud_id      BIGINT       NOT NULL REFERENCES pp_solicitudes(id) ON DELETE CASCADE,

  -- Dónde aterriza en SIESA. Igual a la cuenta de la cabecera salvo en las
  -- réplicas. De acá salen el NIT y la SUCURSAL del conector: teniéndolo en la
  -- línea, el payload sale bien sin que nadie tenga que acordarse.
  cuenta_destino_id BIGINT       NOT NULL REFERENCES pp_cuentas(id) ON DELETE RESTRICT,

  origen            VARCHAR(12)  NOT NULL DEFAULT 'proveedor',
  replica_de_id     BIGINT       REFERENCES pp_solicitud_lineas(id) ON DELETE CASCADE,

  -- Identidad del renglón, tal como se le manda al conector.
  clave_item        TEXT         NOT NULL,
  item              INTEGER      NOT NULL,
  descripcion_item  TEXT,
  unidad_medida     VARCHAR(4)   NOT NULL,

  -- Lo que regía al proponer. Congelado: es la base del cálculo y de la firma.
  precio_actual          NUMERIC(19,4) NOT NULL,
  descuentos_actuales    JSONB         NOT NULL DEFAULT '[]'::jsonb,
  impuestos_vigentes     JSONB         NOT NULL DEFAULT '[]'::jsonb,
  costo_neto_actual      NUMERIC(19,4) NOT NULL,

  -- Lo propuesto.
  precio_propuesto       NUMERIC(19,4) NOT NULL,
  descuentos_propuestos  JSONB         NOT NULL DEFAULT '[]'::jsonb,
  impuestos_propuestos   JSONB         NOT NULL DEFAULT '[]'::jsonb,
  costo_neto_propuesto   NUMERIC(19,4) NOT NULL,
  variacion_pct          NUMERIC(9,4)  NOT NULL,
  porcentaje_max_vigente NUMERIC(5,2),

  fecha_activacion  DATE         NOT NULL,
  notas             VARCHAR(255),

  estado            VARCHAR(20)  NOT NULL DEFAULT 'pendiente',
  motivo_rechazo    TEXT,
  resuelto_at       TIMESTAMPTZ,
  resuelto_por      TEXT,

  siesa_aplicado_at   TIMESTAMPTZ,
  siesa_payload       JSONB,
  siesa_respuesta     JSONB,
  siesa_verificacion  JSONB,

  creado_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT pp_lineas_estado_valido
    CHECK (estado IN (
      'pendiente','aprobada','rechazada','aplicada','fallida','incierto','anulada'
    )),

  -- Heredadas de 001/004/005. Valen igual línea por línea, y por las mismas
  -- razones: un rechazo sin motivo no se puede accionar, y una aplicada sin marca
  -- de empuje es el agujero por donde se cuelan los duplicados.
  CONSTRAINT pp_lineas_rechazo_con_motivo
    CHECK (estado <> 'rechazada'
           OR (motivo_rechazo IS NOT NULL AND btrim(motivo_rechazo) <> '')),

  CONSTRAINT pp_lineas_aplicada_con_marca
    CHECK (estado NOT IN ('aplicada','incierto') OR siesa_aplicado_at IS NOT NULL),

  CONSTRAINT pp_lineas_anulada_sin_empuje
    CHECK (estado <> 'anulada' OR siesa_aplicado_at IS NULL),

  CONSTRAINT pp_lineas_origen_valido
    CHECK (origen IN ('proveedor','replica')),

  -- `origen` y `replica_de_id` dicen lo mismo, así que no pueden discrepar. Una
  -- réplica huérfana sería una línea que nadie sabe de dónde salió, aterrizando en
  -- una sucursal que el proveedor nunca vio.
  CONSTRAINT pp_lineas_replica_coherente
    CHECK ((origen = 'replica') = (replica_de_id IS NOT NULL)),

  -- Una línea no puede ser réplica de sí misma. Ojo con lo que esto NO hace: no
  -- impide que una réplica apunte a OTRA réplica (un CHECK no puede mirar otra
  -- fila). Esa regla —una réplica no se replica, o un grupo de tres sucursales se
  -- multiplica solo— la sostiene el servicio, que solo replica desde líneas con
  -- origen = 'proveedor'.
  CONSTRAINT pp_lineas_replica_no_es_ella_misma
    CHECK (replica_de_id IS NULL OR replica_de_id <> id)
);

COMMENT ON COLUMN pp_solicitud_lineas.impuestos_propuestos IS
  'Los impuestos que el proveedor propone. Un impuesto QUITADO se representa por '
  'AUSENCIA de la entrada, no por valor 0 — igual que los descuentos, y por lo '
  'mismo: la fecha es parte de la llave en SIESA, así que no emitir la fila '
  'significa que ese impuesto no existe en esa fecha. Un valor 0 SÍ es un dato '
  'distinto: dice que el ítem está sujeto al impuesto y hoy paga cero.';

COMMENT ON COLUMN pp_solicitud_lineas.variacion_pct IS
  'Variación del COSTO NETO (precio menos descuentos). NO incluye impuestos, y es '
  'deliberado: meterlos aflojaría el tope justo en los ítems que más plata mueven. '
  'Un cambio de impuesto se controla con revisión humana, no con un umbral.';

COMMENT ON COLUMN pp_solicitud_lineas.origen IS
  'proveedor = la propuso él. replica = la generó el sistema para la sucursal '
  'hermana (pp_grupos_sucursal, migración 007). El proveedor NUNCA ve las réplicas: '
  'lo impide la política de RLS, no el cuidado de quien escribe la consulta.';

CREATE INDEX IF NOT EXISTS idx_pp_lineas_solicitud ON pp_solicitud_lineas(solicitud_id);
CREATE INDEX IF NOT EXISTS idx_pp_lineas_destino   ON pp_solicitud_lineas(cuenta_destino_id);
CREATE INDEX IF NOT EXISTS idx_pp_lineas_estado    ON pp_solicitud_lineas(estado);
CREATE INDEX IF NOT EXISTS idx_pp_lineas_replica   ON pp_solicitud_lineas(replica_de_id);

-- El candado de 001, mudado a la línea y apuntando al DESTINO.
--
-- Que mire el destino y no a quien propone es lo que evita el choque nuevo: si el
-- proveedor tiene habilitadas las dos sucursales hermanas y propone en las dos, la
-- réplica de una chocaría contra la propuesta directa de la otra. Acá la base corta.
CREATE UNIQUE INDEX IF NOT EXISTS idx_pp_lineas_pendiente_unica
  ON pp_solicitud_lineas (cuenta_destino_id, clave_item)
  WHERE estado = 'pendiente';

-- Cola del empuje a SIESA: aprobadas todavía sin marca.
CREATE INDEX IF NOT EXISTS idx_pp_lineas_por_aplicar
  ON pp_solicitud_lineas (id)
  WHERE estado = 'aprobada' AND siesa_aplicado_at IS NULL;


-- ===========================================================================
-- 3. Estado del paquete — derivado, nunca guardado
-- ===========================================================================
CREATE OR REPLACE VIEW pp_solicitudes_resumen AS
SELECT
  s.id,
  s.cuenta_id,
  s.firma_id,
  s.creado_at,
  COUNT(l.id)                                                 AS lineas,
  COUNT(*) FILTER (WHERE l.estado = 'pendiente')              AS pendientes,
  COUNT(*) FILTER (WHERE l.estado IN ('aprobada','aplicada')) AS aprobadas,
  COUNT(*) FILTER (WHERE l.estado = 'rechazada')              AS rechazadas,
  COUNT(*) FILTER (WHERE l.estado = 'anulada')                AS anuladas,
  COUNT(*) FILTER (WHERE l.estado IN ('fallida','incierto'))  AS con_problema,
  COUNT(*) FILTER (WHERE l.origen = 'replica')                AS replicadas,
  -- El resumen sirve para ORDENAR la bandeja, no para decidir: lo que se aprueba
  -- es la línea. Por eso "con_problema" y "pendiente" ganan — son las que piden
  -- que alguien haga algo, y una bandeja las tiene que poner arriba.
  CASE
    WHEN COUNT(*) FILTER (WHERE l.estado IN ('fallida','incierto'))  > 0 THEN 'con_problema'
    WHEN COUNT(*) FILTER (WHERE l.estado = 'pendiente')              > 0 THEN 'pendiente'
    WHEN COUNT(*) FILTER (WHERE l.estado IN ('aprobada','aplicada')) > 0 THEN 'resuelta'
    WHEN COUNT(*) FILTER (WHERE l.estado = 'rechazada')              > 0 THEN 'rechazada'
    ELSE 'anulada'
  END                                                         AS estado_resumen
FROM pp_solicitudes s
LEFT JOIN pp_solicitud_lineas l ON l.solicitud_id = s.id
GROUP BY s.id, s.cuenta_id, s.firma_id, s.creado_at;

COMMENT ON VIEW pp_solicitudes_resumen IS
  'Estado del paquete, DERIVADO de las líneas. No existe una columna `estado` en '
  'pp_solicitudes: sería una segunda fuente de verdad que se va a contradecir el '
  'día que alguien apruebe una línea sin actualizar el padre.';


-- ===========================================================================
-- 4. updated_at
-- ===========================================================================
DROP TRIGGER IF EXISTS trg_pp_solicitudes_nuevas_touch ON pp_solicitudes;
CREATE TRIGGER trg_pp_solicitudes_nuevas_touch BEFORE UPDATE ON pp_solicitudes
  FOR EACH ROW EXECUTE FUNCTION pp_touch_updated_at();

DROP TRIGGER IF EXISTS trg_pp_lineas_touch ON pp_solicitud_lineas;
CREATE TRIGGER trg_pp_lineas_touch BEFORE UPDATE ON pp_solicitud_lineas
  FOR EACH ROW EXECUTE FUNCTION pp_touch_updated_at();


-- ===========================================================================
-- 5. RLS — y acá vive el silencio de la réplica
-- ===========================================================================
ALTER TABLE pp_solicitudes      ENABLE ROW LEVEL SECURITY;
ALTER TABLE pp_solicitud_lineas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pp_solicitudes_nuevas_propias ON pp_solicitudes;
CREATE POLICY pp_solicitudes_nuevas_propias ON pp_solicitudes
  FOR SELECT TO authenticated
  USING (cuenta_id = pp_cuenta_actual());

-- Solo lectura, y SOLO las líneas que él propuso.
--
-- Las réplicas quedan afuera a propósito: el reparto por sede es interno de
-- Merkahorro. Ponerlo en la política, y no en el WHERE de cada consulta, es lo que
-- hace que el silencio no dependa de que alguien se acuerde de filtrar.
--
-- La ESCRITURA pasa siempre por el backend: es el único lugar donde el tope se
-- valida contra el precio que el servidor leyó de SIESA.
DROP POLICY IF EXISTS pp_lineas_propias ON pp_solicitud_lineas;
CREATE POLICY pp_lineas_propias ON pp_solicitud_lineas
  FOR SELECT TO authenticated
  USING (
    origen = 'proveedor'
    AND EXISTS (
      SELECT 1 FROM pp_solicitudes s
       WHERE s.id = pp_solicitud_lineas.solicitud_id
         AND s.cuenta_id = pp_cuenta_actual()
    )
  );


-- ===========================================================================
-- 6. Backfill — cada solicitud vieja pasa a ser un paquete de una sola línea
-- ===========================================================================
-- Idempotente: `WHERE NOT EXISTS` sobre el id viejo. Correrlo dos veces no duplica.

ALTER TABLE pp_solicitud_lineas
  ADD COLUMN IF NOT EXISTS migrada_de_id BIGINT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_pp_lineas_migrada_de
  ON pp_solicitud_lineas(migrada_de_id) WHERE migrada_de_id IS NOT NULL;

COMMENT ON COLUMN pp_solicitud_lineas.migrada_de_id IS
  'id en pp_solicitudes_precio (la tabla previa a la 006). NULL en todo lo nuevo. '
  'Sirve para verificar el backfill antes de borrar la tabla vieja.';

DO $migracion$
DECLARE
  v         RECORD;
  nueva_id  BIGINT;
BEGIN
  FOR v IN
    SELECT p.* FROM pp_solicitudes_precio p
     WHERE NOT EXISTS (
       SELECT 1 FROM pp_solicitud_lineas l WHERE l.migrada_de_id = p.id
     )
     ORDER BY p.id
  LOOP
    INSERT INTO pp_solicitudes (cuenta_id, firma_id, creado_at, updated_at)
    VALUES (v.cuenta_id, v.firma_id, v.creado_at, v.updated_at)
    RETURNING id INTO nueva_id;

    INSERT INTO pp_solicitud_lineas (
      solicitud_id, cuenta_destino_id, origen,
      clave_item, item, descripcion_item, unidad_medida,
      precio_actual, descuentos_actuales, impuestos_vigentes, costo_neto_actual,
      precio_propuesto, descuentos_propuestos, impuestos_propuestos,
      costo_neto_propuesto, variacion_pct, porcentaje_max_vigente,
      fecha_activacion, notas,
      estado, motivo_rechazo, resuelto_at, resuelto_por,
      siesa_aplicado_at, siesa_payload, siesa_respuesta, siesa_verificacion,
      creado_at, updated_at, migrada_de_id
    ) VALUES (
      nueva_id, v.cuenta_id, 'proveedor',
      v.clave_item, v.item, v.descripcion_item, v.unidad_medida,
      v.precio_actual, v.descuentos_actuales, v.impuestos_vigentes, v.costo_neto_actual,
      v.precio_propuesto, v.descuentos_propuestos,
      -- Antes de esta migración los impuestos NO se editaban: se re-emitían tal
      -- cual. Copiarlos de `vigentes` no es una suposición — es exactamente lo que
      -- el sistema le mandó a SIESA.
      v.impuestos_vigentes,
      v.costo_neto_propuesto, v.variacion_pct, v.porcentaje_max_vigente,
      v.fecha_activacion, v.notas,
      v.estado, v.motivo_rechazo, v.resuelto_at, v.resuelto_por,
      v.siesa_aplicado_at, v.siesa_payload, v.siesa_respuesta, v.siesa_verificacion,
      v.creado_at, v.updated_at, v.id
    );
  END LOOP;
END $migracion$;


-- ===========================================================================
-- 7. La tabla vieja: se conserva, NO se borra acá
-- ===========================================================================
-- Verificar antes de borrarla. Los dos conteos tienen que dar igual:
--
--   SELECT count(*) FROM pp_solicitudes_precio;
--   SELECT count(*) FROM pp_solicitud_lineas WHERE migrada_de_id IS NOT NULL;
--
-- Y que ninguna haya cambiado de estado en el camino (tiene que dar 0 filas):
--
--   SELECT p.id, p.estado AS viejo, l.estado AS nuevo
--     FROM pp_solicitudes_precio p
--     JOIN pp_solicitud_lineas l ON l.migrada_de_id = p.id
--    WHERE p.estado <> l.estado;
--
-- Recién con eso en cero va el DROP, en una migración aparte.

COMMENT ON TABLE pp_solicitudes_precio IS
  'LEGACY (hasta la migración 006). Reemplazada por pp_solicitudes + '
  'pp_solicitud_lineas. Se conserva para verificar el backfill; el backend ya no '
  'la escribe. Borrar en una migración aparte, después de comprobar los conteos.';
