-- ---------------------------------------------------------------------------
-- 007 — Sucursales hermanas: una cotización, varias sucursales del mismo NIT
-- ---------------------------------------------------------------------------
--
-- QUÉ RESUELVE
-- Un mismo proveedor entrega en Copacabana y en el resto, y SIESA lo guarda como
-- dos sucursales del mismo NIT. Es el mismo acuerdo comercial partido por zona de
-- entrega:
--
--     900256457  suc 001  COPA ZONA 2 RAMA   ↔  suc 002  ZONA 2 RAMA
--     900256457  suc 003  COPA ZONA 2 EL REY ↔  suc 004  ZONA 2 EL REY
--     900256457  suc 006  COPA ZONA 2 NIVEA  ↔  suc 005  ZONA 2 NIVEA
--
-- Hoy el proveedor tendría que proponer el mismo precio dos veces. Con esto lo
-- propone una y el sistema replica a la hermana, en silencio (ver la política de
-- RLS de la migración 006: el proveedor no ve las líneas replicadas).
--
-- POR QUÉ UN GRUPO Y NO UN PAR
-- Un par es direccional y habría que guardar las dos direcciones para que
-- proponer desde cualquiera de las dos alcance a la otra. Un grupo es simétrico
-- por construcción: replicar es "a los demás miembros". Y si mañana aparece una
-- tercera sucursal, entra sin cambiar el modelo.
--
-- ⚠️ POR QUÉ NACEN APAGADOS (`activo = false`)
-- Medido sobre datos reales el 2026-09-06, cruzando la consulta de terceros
-- (3.913 filas) contra la de cotizaciones (18.870): de 521 renglones comparados
-- entre sucursales hermanas,
--
--     449  tienen el MISMO precio
--      16  tienen precio DISTINTO  ← ZONA 2 NIVEA: $17.260 contra $17.290
--      43  existen SOLO en la sucursal COPA
--      13  existen SOLO en la otra
--
-- O sea: es FALSO que las hermanas siempre valgan lo mismo, y es falso que
-- tengan el mismo catálogo. Un grupo que se activa solo pisaría 16 diferencias
-- que alguien puso a propósito, sin que nadie se entere.
--
-- Por eso las filas de abajo son SUGERENCIAS. Nada se replica hasta que compras
-- prende el grupo. Prenderlo es un clic; deshacer un precio ya escrito en SIESA
-- es ir a pedir que lo borren.
--
-- POR QUÉ LA SUGERENCIA SE DERIVA Y NO SE HARDCODEA
-- Si pegara acá los 30 pares que detecté hoy, la lista envejece el día que SIESA
-- da de alta la sucursal 011. El bloque del final los busca en `pp_cuentas` con la
-- misma regla, así que se puede volver a correr cuando el maestro crezca.
--
-- LO QUE LA REGLA NO PUEDE SABER
-- El prefijo COPA/COPACABANA es una convención de nombre, no un dato. Detecté 14
-- sucursales "COPA X" sin hermana, y casos donde el prefijo es parte del nombre
-- real (FERRETERIA DECOPA, MUNICIPIO DE COPACABANA). Por eso el resultado es una
-- sugerencia apagada que un humano confirma, nunca una verdad.
-- ---------------------------------------------------------------------------


-- ===========================================================================
-- 1. El grupo
-- ===========================================================================
CREATE TABLE IF NOT EXISTS pp_grupos_sucursal (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nit             VARCHAR(15)  NOT NULL REFERENCES pp_proveedores(nit) ON DELETE CASCADE,
  nombre          TEXT         NOT NULL,
  activo          BOOLEAN      NOT NULL DEFAULT false,
  origen          VARCHAR(12)  NOT NULL DEFAULT 'sugerido',
  confirmado_por  TEXT,
  confirmado_at   TIMESTAMPTZ,
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT pp_grupos_origen_valido
    CHECK (origen IN ('sugerido','manual')),

  -- Un grupo activo tiene que decir QUIÉN lo activó. Es la persona que se hizo
  -- cargo de que esas sucursales comparten precio: si mañana se pisa una
  -- diferencia, la pregunta "¿quién dijo que estas dos eran la misma?" tiene
  -- respuesta.
  CONSTRAINT pp_grupos_activo_con_responsable
    CHECK (activo = false
           OR (confirmado_por IS NOT NULL AND confirmado_at IS NOT NULL))
);

COMMENT ON TABLE pp_grupos_sucursal IS
  'Sucursales del mismo NIT que comparten precio. Nacen APAGADAS: la sugerencia '
  'automática por nombre acierta casi siempre, y "casi siempre" no alcanza cuando '
  'lo que se pisa es un precio.';

COMMENT ON COLUMN pp_grupos_sucursal.origen IS
  'sugerido = lo detectó la regla de nombre (prefijo COPA/COPACABANA). '
  'manual = lo armó un admin. La distinción importa: una sugerencia no verificada '
  'no es lo mismo que una decisión de compras.';

CREATE INDEX IF NOT EXISTS idx_pp_grupos_nit    ON pp_grupos_sucursal(nit);
CREATE INDEX IF NOT EXISTS idx_pp_grupos_activo ON pp_grupos_sucursal(activo) WHERE activo;


-- ===========================================================================
-- 2. Los miembros
-- ===========================================================================
CREATE TABLE IF NOT EXISTS pp_grupo_sucursales (
  grupo_id    BIGINT       NOT NULL REFERENCES pp_grupos_sucursal(id) ON DELETE CASCADE,
  nit         VARCHAR(15)  NOT NULL,
  sucursal    VARCHAR(3)   NOT NULL,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

  PRIMARY KEY (grupo_id, nit, sucursal),

  -- Apunta a una cuenta que existe de verdad. Sin esto, un grupo puede nombrar
  -- una sucursal fantasma y la réplica falla recién al aprobar, con el proveedor
  -- esperando.
  CONSTRAINT pp_grupo_sucursales_cuenta
    FOREIGN KEY (nit, sucursal) REFERENCES pp_cuentas(nit, sucursal) ON DELETE CASCADE
);

-- Una sucursal en UN SOLO grupo. Si estuviera en dos, una propuesta se replicaría
-- dos veces sobre el mismo destino y chocaría contra
-- `idx_pp_lineas_pendiente_unica` — pero recién al enviar, con el error en la cara
-- del proveedor por un problema de configuración que no es suyo.
CREATE UNIQUE INDEX IF NOT EXISTS idx_pp_grupo_sucursal_unica
  ON pp_grupo_sucursales(nit, sucursal);

COMMENT ON TABLE pp_grupo_sucursales IS
  'Miembros del grupo. La réplica va "a los demás miembros": simétrica, así que '
  'proponer desde cualquiera de las sucursales alcanza a las otras.';

DROP TRIGGER IF EXISTS trg_pp_grupos_touch ON pp_grupos_sucursal;
CREATE TRIGGER trg_pp_grupos_touch BEFORE UPDATE ON pp_grupos_sucursal
  FOR EACH ROW EXECUTE FUNCTION pp_touch_updated_at();


-- ===========================================================================
-- 3. RLS — invisibles para el proveedor
-- ===========================================================================
-- Con RLS activo y SIN políticas, la base niega todo a `authenticated`: solo se
-- leen con la service key, desde el backend. Es el mismo criterio que
-- `pp_proveedores` (que guarda el tope). El agrupamiento por sede es interno de
-- Merkahorro y el proveedor no tiene por qué verlo.
ALTER TABLE pp_grupos_sucursal  ENABLE ROW LEVEL SECURITY;
ALTER TABLE pp_grupo_sucursales ENABLE ROW LEVEL SECURITY;


-- ===========================================================================
-- 4. Sugerencias — APAGADAS. Se pueden volver a correr cuando crezca el maestro.
-- ===========================================================================
DO $sugerencias$
DECLARE
  par  RECORD;
  gid  BIGINT;
  n    INTEGER := 0;
BEGIN
  FOR par IN
    WITH normalizadas AS (
      SELECT c.nit,
             c.sucursal,
             btrim(regexp_replace(upper(COALESCE(c.nombre_sucursal, '')), '\s+', ' ', 'g')) AS nom
        FROM pp_cuentas c
       WHERE COALESCE(c.nombre_sucursal, '') <> ''
    ),
    con_prefijo AS (
      -- COPACABANA va PRIMERO en la alternancia: al revés, "COPACABANA X" se
      -- convertiría en "CABANA X" y no encontraría a su hermana.
      SELECT nit, sucursal, nom,
             btrim(regexp_replace(nom, '^(COPACABANA|COPA)[ -]+', '')) AS raiz
        FROM normalizadas
       WHERE nom ~ '^(COPACABANA|COPA)[ -]+'
    )
    SELECT p.nit, p.raiz,
           p.sucursal AS suc_copa,
           h.sucursal AS suc_base
      FROM con_prefijo p
      JOIN normalizadas h
        ON h.nit = p.nit
       AND h.nom = p.raiz
       AND h.sucursal <> p.sucursal   -- el mismo nombre en la misma sucursal no es par
     WHERE p.raiz <> ''
     ORDER BY p.nit, p.sucursal
  LOOP
    -- Idempotente: si cualquiera de las dos ya está en un grupo, no se toca. Así
    -- este bloque se puede volver a correr sin pisar lo que compras ya confirmó.
    CONTINUE WHEN EXISTS (
      SELECT 1 FROM pp_grupo_sucursales g
       WHERE g.nit = par.nit
         AND g.sucursal IN (par.suc_copa, par.suc_base)
    );

    INSERT INTO pp_grupos_sucursal (nit, nombre, activo, origen)
    VALUES (par.nit, par.raiz, false, 'sugerido')
    RETURNING id INTO gid;

    INSERT INTO pp_grupo_sucursales (grupo_id, nit, sucursal)
    VALUES (gid, par.nit, par.suc_copa),
           (gid, par.nit, par.suc_base);

    n := n + 1;
  END LOOP;

  RAISE NOTICE 'Grupos sugeridos creados: % (todos APAGADOS — compras los confirma)', n;
END $sugerencias$;


-- ===========================================================================
-- 5. Qué mirar después de correrla
-- ===========================================================================
-- Las sugerencias, con cuántos ítems tiene cada sucursal:
--
--   SELECT g.id, g.nit, g.nombre, g.activo,
--          string_agg(m.sucursal || ' (' || COALESCE(q.items, 0) || ' ítems)', '  ↔  ')
--     FROM pp_grupos_sucursal g
--     JOIN pp_grupo_sucursales m ON m.grupo_id = g.id
--     LEFT JOIN (
--       SELECT nit, sucursal, count(*) AS items FROM pp_cotizaciones GROUP BY 1, 2
--     ) q ON q.nit = m.nit AND q.sucursal = m.sucursal
--    GROUP BY g.id, g.nit, g.nombre, g.activo
--    ORDER BY g.nit;
--
-- Y ANTES de prender uno, mirar en qué difieren sus dos sucursales. Si acá salen
-- filas, prenderlo va a pisar esos precios:
--
--   -- reemplazar :nit, :suc_a y :suc_b
--   SELECT a.item, a.descripcion_item, a.unidad_medida, a.precio AS precio_a, b.precio AS precio_b
--     FROM pp_cotizaciones a
--     JOIN pp_cotizaciones b
--       ON b.nit = a.nit AND b.item = a.item
--      AND b.unidad_medida = a.unidad_medida
--      AND b.fecha_activacion = a.fecha_activacion
--    WHERE a.nit = :nit AND a.sucursal = :suc_a AND b.sucursal = :suc_b
--      AND a.precio IS DISTINCT FROM b.precio;
